### ISSUE TITLE
[Feature] MainViewModel 구현

### ISSUE THREAD

**Issue by ryuchanghwi** [ryuchanghwi/ExchangeRateCalc#23]
## 📌  Feature Issue

- MainViewModel 구현

## 📝  To-do

Input 사항
- [ ] ViewDidLoad시 api 통신
- [ ] 숫자 입력
Output 사항
- [ ] api 통신 결과 반환
- [ ] 숫자 결과 반환
- [ ] 제약 사항 반환
